apiVersion: v1
kind: ConfigMap
metadata:
  name: intelligenceapi-auth-config
  namespace: {{ .Values.namespace }}
data:
  SECRET_KEY: {{ .Values.auth.secretKey }}
  GITHUB_CLIENT_ID: {{ .Values.auth.githubClientId }}
  GITHUB_CLIENT_SECRET: {{ .Values.auth.githubClientSecret }}
  REDIRECT_URI: {{ .Values.auth.redirectUri }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intelligenceapi-auth
  namespace: {{ .Values.namespace }}
  labels:
    app: intelligenceapi-auth
spec:
  replicas: {{ .Values.auth.replicaCount }}
  selector:
    matchLabels:
      app: intelligenceapi-auth
  template:
    metadata:
      labels:
        app: intelligenceapi-auth
    spec:
      containers:
      - name: intelligenceapi-auth
        image: {{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag }}
        imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
        ports:
        - containerPort: 8000
        env:
        - name: MYSQL_HOST
          value: intelligenceapi-mysql-service
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database }}
        - name: MYSQL_USER
          value: {{ .Values.mysql.user }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.mysql.password }}
        envFrom:
        - configMapRef:
            name: intelligenceapi-auth-config
---
apiVersion: v1
kind: Service
metadata:
  name: intelligenceapi-auth
  namespace: {{ .Values.namespace }}
  labels:
    app: intelligenceapi-auth
spec:
  selector:
    app: intelligenceapi-auth
  ports:
  - protocol: TCP
    name: http
    port: {{ .Values.auth.service.port }}
    targetPort: 8000
