apiVersion: apps/v1
kind: Deployment
metadata:
  name: intelligenceapi-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    app: intelligenceapi-redis
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app: intelligenceapi-redis
  template:
    metadata:
      labels:
        app: intelligenceapi-redis
    spec:
      containers:
      - name: intelligenceapi-redis
        image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: intelligenceapi-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    app: intelligenceapi-redis
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    app: intelligenceapi-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
