apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: intelligenceapi-mysql-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intelligenceapi-mysql
  namespace: {{ .Values.namespace }}
  labels:
    app: intelligenceapi-mysql
spec:
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
      app: intelligenceapi-mysql
  template:
    metadata:
      labels:
        app: intelligenceapi-mysql
    spec:
      containers:
      - name: intelligenceapi-mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.rootPassword }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database }}
        - name: MYSQL_USER
          value: {{ .Values.mysql.user }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.mysql.password }}
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: intelligenceapi-mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: intelligenceapi-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: intelligenceapi-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: intelligenceapi-mysql-service
  namespace: {{ .Values.namespace }}
  labels:
    app: intelligenceapi-mysql
spec:
  selector:
    app: intelligenceapi-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
