---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: intelligenceapi-mysql-pvc
  namespace: ns-intelligenceapi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intelligenceapi-mysql
  namespace: ns-intelligenceapi
  labels:
    app: intelligenceapi-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intelligenceapi-mysql
  template:
    metadata:
      labels:
        app: intelligenceapi-mysql
    spec:
      containers:
      - name: intelligenceapi-mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        - name: MYSQL_DATABASE
          value: auth_db
        - name: MYSQL_USER
          value: auth_user
        - name: MYSQL_PASSWORD
          value: authpassword
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: intelligenceapi-mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: intelligenceapi-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: intelligenceapi-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: intelligenceapi-mysql-service
  namespace: ns-intelligenceapi
  labels:
    app: intelligenceapi-mysql
spec:
  selector:
    app: intelligenceapi-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: intelligenceapi-auth-config
  namespace: ns-intelligenceapi
data:
  SECRET_KEY: your_secret_key
  GITHUB_CLIENT_ID: your_github_client_id
  GITHUB_CLIENT_SECRET: your_github_client_secret
  REDIRECT_URI: http://localhost:8000/auth/callback
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intelligenceapi-auth
  namespace: ns-intelligenceapi
  labels:
    app: intelligenceapi-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: intelligenceapi-auth
  template:
    metadata:
      labels:
        app: intelligenceapi-auth
    spec:
      containers:
      - name: intelligenceapi-auth
        image: nerdynot/intelligenceapi-auth:latest
        ports:
        - containerPort: 8000
        env:
        - name: MYSQL_HOST
          value: mysql-service
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: auth_db
        - name: MYSQL_USER
          value: auth_user
        - name: MYSQL_PASSWORD
          value: authpassword
        envFrom:
        - configMapRef:
            name: intelligenceapi-auth-config
---
apiVersion: v1
kind: Service
metadata:
  name: intelligenceapi-auth
  namespace: ns-intelligenceapi
  labels:
    app: intelligenceapi-auth
spec:
  selector:
    app: intelligenceapi-auth
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8000
