---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intelligenceapi-redis
  namespace: ns-intelligenceapi
  labels:
    app: intelligenceapi-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intelligenceapi-redis
  template:
    metadata:
      labels:
        app: intelligenceapi-redis
    spec:
      containers:
      - name: intelligenceapi-redis
        image: redis/redis-stack:latest
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: intelligenceapi-redis
  namespace: ns-intelligenceapi
  labels:
    app: intelligenceapi-redis
spec:
  selector:
    app: intelligenceapi-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
