apiVersion: apps/v1
kind: Deployment
metadata:
  name: intelligenceapi-storage
  namespace: ns-intelligenceapi
  labels:
    app: intelligenceapi-storage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: intelligenceapi-storage
  template:
    metadata:
      labels:
        app: intelligenceapi-storage
    spec:
      containers:
      - name: intelligenceapi-storage
        image: nerdynot/intelligenceapi-storage:latest
        ports:
        - containerPort: 8000
        env:
        # Set the LLM provider (e.g., 'azure', 'openai', 'gemini', 'vertexai', 'anthropic')
        - name: LLM_PROVIDER
          value: "Your LLM provider"
        # Set the API key for the chosen LLM provider
        - name: LLM_API_KEY
          value: "Your LLM api key"
        # Set the model name for the chosen LLM provider
        - name: LLM_MODEL
          value: "Your LLM model"
        # Set the temperature for the model's response generation (lower for deterministic, higher for creative responses)
        - name: LLM_TEMPERATURE
          value: "0.5"
        # Set the Azure endpoint if the LLM provider is 'azure'
        - name: AZURE_ENDPOINT
          value: "Your Azure endpoint"
        # Set the Azure API version if the LLM provider is 'azure'
        - name: AZURE_API_VERSION
          value: "Your Azure API version"
        # Set the Embedding provider (e.g., 'azure', 'openai', 'gemini', 'vertexai')
        - name: EMBEDDING_PROVIDER
          value: "Your embedding provider"
        # Set the API key for the chosen Embedding provider
        - name: EMBEDDING_API_KEY
          value: "Your embedding api key"
        # Set the model name for the chosen Embedding provider
        - name: EMBEDDING_MODEL
          value: "Your embedding model"
        # Set the storage provider (e.g., 'azure', 'aws')
        - name: STORAGE_PROVIDER
          value: "Your storage provider"
        # Set the Azure connection string if using Azure as the storage provider
        - name: AZURE_CONNECTION_STRING
          value: "Your Azure connection string"
        # Set the Azure container name if using Azure as the storage provider
        - name: AZURE_CONTAINER_NAME
          value: "Your Azure container name"
        # Set the Azure account name if using Azure as the storage provider
        - name: AZURE_ACCOUNT_NAME
          value: "Your Azure storage account name"
        # Set the AWS access key ID if using AWS as the storage provider
        - name: AWS_ACCESS_KEY_ID
          value: "Your AWS access key id"
        # Set the AWS secret access key if using AWS as the storage provider
        - name: AWS_SECRET_ACCESS_KEY
          value: "Your AWS secret access key"
        # Set the AWS region if using AWS as the storage provider
        - name: AWS_REGION
          value: "Your AWS region"
        # Set the Redis URL if Redis is used for caching or other purposes
        - name: REDIS_URL
          value: "Your Redis URL"
        # Set the Redis index name if Redis is used for indexing
        - name: REDIS_INDEX_NAME
          value: "Your Redis index name"
---
apiVersion: v1
kind: Service
metadata:
  name: intelligenceapi-storage
  namespace: ns-intelligenceapi
  labels:
    app: intelligenceapi-storage
spec:
  selector:
    app: intelligenceapi-storage
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8000
