# Global settings section:
# This section defines settings that are common across the entire application.
global:
  namespace: ns-intelligenceapi  # Namespace where resources will be deployed.
  image:
    pullPolicy: IfNotPresent  # Image pull policy.
  service:
    type: ClusterIP  # Default service type.
    port: 80  # Default service port.
  llm:  # Language Model (LLM) service settings.
    provider: "Your LLM provider"  # LLM provider (e.g., OpenAI, Azure).
    apiKey: "Your LLM api key"  # API key for LLM provider.
    model: "Your LLM model"  # Specific LLM model to use.
    temperature: "0.5"  # Temperature setting for LLM.
    azureEndpoint: "Your Azure endpoint"  # Azure-specific LLM endpoint.
    azureApiVersion: "Your Azure API version"  # Azure API version.

  embedding:  # Embedding service settings.
    provider: "Your embedding provider"  # Embedding service provider.
    apiKey: "Your embedding api key"  # API key for embedding service.
    model: "Your embedding model"  # Specific embedding model to use.

  redis:  # Redis settings.
    url: "Your Redis URL"  # Redis connection URL.
    indexName: "Your Redis index name"  # Redis index name.

# Gateway API service settings:
gatewayapi:
  replicaCount: 2  # Number of replicas.
  image:
    repository: nerdynot/intelligenceapi-gatewayapi  # Image repository.
    tag: latest  # Image tag.

# Query service settings:
query:
  replicaCount: 2  # Number of replicas.
  image:
    repository: nerdynot/intelligenceapi-query  # Image repository.
    tag: latest  # Image tag.
  service: *global.service  # Service settings (inherited from global).
  llm: *global.llm  # LLM settings (inherited from global).
  embedding: *global.embedding  # Embedding settings (inherited from global).
  redis: *global.redis  # Redis settings (inherited from global).

# Analysis service settings:
analysis:
  replicaCount: 2  # Number of replicas.
  image:
    repository: nerdynot/intelligenceapi-analysis  # Image repository.
    tag: latest  # Image tag.
  service: *global.service  # Service settings (inherited from global).
  llm: *global.llm  # LLM settings (inherited from global).
  embedding: *global.embedding  # Embedding settings (inherited from global).

# Auth service settings:
auth:
  replicaCount: 2  # Number of replicas.
  image:
    repository: nerdynot/intelligenceapi-auth  # Image repository.
    tag: latest  # Image tag.
  service: *global.service  # Service settings (inherited from global).
  secretKey: your_secret_key  # Secret key for authentication.
  githubClientId: your_github_client_id  # GitHub client ID.
  githubClientSecret: your_github_client_secret  # GitHub client secret.
  redirectUri: http://localhost:8000/auth/callback  # Redirect URI for GitHub OAuth.

# MySQL database settings:
mysql:
  rootPassword: rootpassword  # Root password for MySQL.
  database: auth_db  # MySQL database name.
  user: auth_user  # MySQL username.
  password: authpassword  # MySQL user password.
  storage: 1Gi  # Storage size for MySQL.
  replicaCount: 1  # Number of replicas.

# Redis settings:
redis:
  replicaCount: 1  # Number of replicas.
  image:
    repository: redis/redis-stack  # Image repository.
    tag: latest  # Image tag.

# Storage service settings:
storage:
  replicaCount: 2  # Number of replicas.
  image:
    repository: nerdynot/intelligenceapi-storage  # Image repository.
    tag: latest  # Image tag.
    pullPolicy: *global.image.pullPolicy  # Image pull policy (inherited from global).
  service:
    type: *global.service.type  # Service type (inherited from global).
    port: *global.service.port  # Service port (inherited from global).
  llm: *global.llm  # LLM settings (inherited from global).
  embedding: *global.embedding  # Embedding settings (inherited from global).
  storageProvider: "Your storage provider"  # Storage provider (e.g., Azure, S3).
  azure:
    connectionString: "Your Azure connection string"  # Azure connection string.
    containerName: "Your Azure container name"  # Azure container name.
    accountName: "Your Azure storage account name"  # Azure storage account name.
  aws:
    accessKeyId: "Your AWS access key id"  # AWS access key ID.
    secretAccessKey: "Your AWS secret access key"  # AWS secret access key.
    region: "Your AWS region"  # AWS region.
  redis: *global.redis  # Redis settings (inherited from global).

# Webhook service settings:
webhook:
  replicaCount: 2  # Number of replicas.
  image:
    repository: nerdynot/intelligenceapi-webhook  # Image repository.
    tag: latest  # Image tag.
    pullPolicy: IfNotPresent  # Image pull policy.
  slackWebhookUrlCSP: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK/CSP"  # Slack webhook URL for CSP analysis.
  slackWebhookUrlDevops: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK/DEVOPS"  # Slack webhook URL for DevOps analysis.
  messageLanguage: "English"  # Language for Slack messages.
  service:
    type: ClusterIP  # Service type.
    port: 80  # Service port.
