name: IntelligenceAPI Storage Service Build and Push

on:
  push:
    paths:
      - 'api-services/storage/**'
  pull_request:
    paths:
      - 'api-services/storage/**'

jobs:
  query-api_build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Extract branch name
      id: extract_branch
      run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

    - name: Extract short SHA
      id: extract_sha
      run: echo "::set-output name=sha_short::$(echo ${{ github.sha }} | cut -c1-5)"

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./api-services/storage
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/intelligenceapi-storage:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/intelligenceapi-storage:${{ steps.extract_branch.outputs.branch }}-${{ steps.extract_sha.outputs.sha_short }}
